version: '3'

services:
  php:
    build: ./docker/php
    links:
      - mysql
    ports:
      - 10080:80
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: seminar
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - data-mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
  data-mysql:
